### ISSUE TITLE
Install fails on debian buster

### ISSUE THREAD

**Issue by darkoverlordofdata** [MulleFoundation/foundation-developer#3]
I'm following these install instructions: [https://github.com/MulleFoundation/foundation-developer](https://github.com/MulleFoundation/foundation-developer) and they are not working. 
I tried both ways:
* entering the gpg keys
* running the apt-installer script. 
Both get the following issue:
```
Installing foundation-developer packages (up to 1 GB)...
Hit:1 http://deb.debian.org/debian buster-backports InRelease
Hit:2 http://packages.microsoft.com/repos/vscode stable InRelease
Hit:3 https://deb.debian.org/debian buster InRelease
Ign:4 https://dl.bintray.com/dryzig/zig-debian buster InRelease
Hit:5 https://deb.nodesource.com/node_12.x buster InRelease
Ign:6 https://dl.bintray.com/sbt/debian  InRelease
Hit:7 https://packages.microsoft.com/debian/10/prod buster InRelease
Get:8 https://dl.bintray.com/dryzig/zig-debian buster Release [1,840 B]
Ign:9 https://storage.googleapis.com/cros-packages/80 buster InRelease
Get:10 https://dl.bintray.com/sbt/debian  Release [815 B]
Hit:11 https://deb.debian.org/debian-security buster/updates InRelease
Hit:12 https://storage.googleapis.com/cros-packages/80 buster Release
Ign:13 http://download.codeon.de buster InRelease
Err:14 http://www.mulle-kybernetik.com buster InRelease
  500  Internal Server Error [IP: 138.201.123.71 80]
Err:16 http://download.codeon.de buster Release
  404  Not Found [IP: 78.46.153.209 80]
Hit:15 https://apt.llvm.org/buster llvm-toolchain-buster-8 InRelease
Reading package lists...
E: The repository 'http://download.codeon.de buster Release' does not have a Release file.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package foundation-developer
```
and so when I follow up with sudo apt install foundation-developer I of course get this error:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package foundation-developer
```

**Comment by codeon-nat** [comment]
Here is  a quick tip, since I am not near linux right now:

The repositories are ubuntu named so `buster`  is actually `bionic`. If you can change this in `/etc/apt.d/conf.d/*codeon*` (I forgot the exact filename) and then `apt-get update`, you should be OK. You probably also will have to change this for `/etc/apt.d/conf.d/*mulle-kybernetik*`. A nicer solution would be preferable though.

**Comment by codeon-nat** [comment]
I put some symlinks into the mulle-kybernetik repository, so that buster refers to bionic. It could work now... maybe...

**Comment by darkoverlordofdata** [comment]
I changed 'buster' to 'bionic' in these 2 files:

* /etc/apt/sources.list.d/mulle-kybernetik.com-main.list
* /etc/apt/sources.list.d/codeon.de-main.list

and that worked. Thanks.

**Comment by darkoverlordofdata** [comment]
1 more error -
```
mulle-clang --version
mulle-clang: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```
I resolved using:
```
sudo apt install libncurses5
```

**Comment by mulle-nat** [comment]
Interesting, I will put it into the install instructions. Thanks for your feedback! Very helpful.
