### ISSUE TITLE
Please offer prebuilt binaries of mulle-clang for MSYS2

### ISSUE THREAD

**Issue by 3oheicrw** [MulleFoundation/foundation-developer#5]
On the release page there is only 32 bit builds for Windows x86 with MSVC:

https://github.com/mulle-cc/mulle-clang-project/releases

The latest release even doesn't have Windows builds.

I followed your instructions to build mulle-clang from source on MSYS2. It failed to link with MINGW64 and binutils. I have to use CLANG64 and LLVM tools. For unknown reasons, the generated LLVM binaries are very large. They are all more than 1 GB in size. This is the first time I see executables that big. The DLL itself also more than 1 GB in size. This could be the reason why binutils failed to link them. From my experience LLVM tools are more efficient to deal with large binaries than GNU binutils. But back to the original problem, I can't use a mulle-clang that large. It exhausted all of my disk space and I have to cancel ninja install.

Either please give us a working config for MSYS2 so we could build it ourselves or give us prebuilt binaries please. We are on legacy Windows without the WSL so you can't tell us to use the Linux version.

@mulle-nat @codeon-nat @mulle-kybernetik-tv

**Comment by 3oheicrw** [comment]
https://github.com/msys2/MINGW-packages/issues/10501

**Comment by mulle-nat** [comment]
So as this is marked completed, I guess you got it to work ?

**Comment by 3oheicrw** [comment]
> So as this is marked completed, I guess you got it to work ?

No. I think no one cares. Better close it.

**Comment by 3oheicrw** [comment]
> 12 hours ago _you_ at least seemed to care, but then something happened. What I don't know. Anyway you closed it already.

Then want me to open it again? Anyway **the problem is still there**. I know this project since it's first go public. It's cool but I have no use for ObjC. I recall just some previous version I still could build it without any problems on MSYS2. Now things turned so bad. You see the package request on MSYS2 repo I posted above? Exactly at this point in time, mulle-clang still compiles fine with MSYS2, MSYS2 MINGW64, not even MSYS2 CLANG64. I feel being abandoned. You moved to embrace MSVC and WSL, it's up to you. I'm on legacy Windows and I don't have such a thing. Don't tell me to upgrade.

You are the project owner you could open or close ticket at will. If you cared about it you could reopen it. But I will not. I'm done with this. If you continue insisting **if it's closed then it's no longer a problem** then... it's OK. You didn't care about us MSYS2 users already. It's nothing new.

**Comment by mulle-nat** [comment]
Dude chill. First up, you closed it yourself, before I even responded.

Then making a package takes time. When I get zero feedback from users, I assume noone is using. So why would I waste my time to build packages, I don't even use myself ?  There is a note in the [https://github.com/mulle-cc/mulle-clang-project/releases/tag/14.0.6.1](). 

> If you need pre-built binaries or bottles for some platform, put up an "issue".

So you put up an issue, but then close it. What do you think happens ?

**Comment by 3oheicrw** [comment]
> Dude chill. First up, you closed it yourself, before I even responded.
> 
> Then making a package takes time. When I get zero feedback from users, I assume noone is using. So why would I waste my time to build packages, I don't even use myself ? There is a note in the https://github.com/mulle-cc/mulle-clang-project/releases/tag/14.0.6.1.
> 
> > If you need pre-built binaries or bottles for some platform, put up an "issue".
> 
> So you put up an issue, but then close it. What do you think happens ?

You don't need to provide prebuilt binaries. Please give me a guide that works. Currently it's: read LLVM guide and try it yourself. There used to be a shell script to help building so the users don't have to deal with cmake directly, unfortunately you deleted it. BTW, there are alternatives to your project: GNUStep's libobjc2 with vanilla clang or ObjFW with vanilla clang. Yours is the only needs a modified clang.

**Comment by mulle-nat** [comment]
Let's get this in sequence:

* I provide prebuilt binaries on request only. You requested then closed -> no binaries
* There are scripts provided to build everything, see [clang/bin](https://github.com/mulle-cc/mulle-clang-project/tree/mulle/14.0.6/clang/bin)
* The build guide with bash for windows [clang/BUILD_MULLE_CLANG.md](https://github.com/mulle-cc/mulle-clang-project/blob/mulle/14.0.6/clang/BUILD_MULLE_CLANG.md) is still there as far as I can see. I don't know, if it still works though.
* Iif you prefer other projects using the stock compiler, i have no problems with that.

Anyway I built a windows package overnight to short-circuit this dialogue. I hope the package works for you. I can't do anything about the compiler size.

See Assets in [14.0.6.1](https://github.com/mulle-cc/mulle-clang-project/releases/tag/14.0.6.1).

**Comment by 3oheicrw** [comment]
> Let's get this in sequence:
> 
> * I provide prebuilt binaries on request only. You requested then closed -> no binaries
> * There are scripts provided to build everything, see [clang/bin](https://github.com/mulle-cc/mulle-clang-project/tree/mulle/14.0.6/clang/bin)
> * The build guide with bash for windows [clang/BUILD_MULLE_CLANG.md](https://github.com/mulle-cc/mulle-clang-project/blob/mulle/14.0.6/clang/BUILD_MULLE_CLANG.md) is still there as far as I can see. I don't know, if it still works though.
> * If you prefer other projects using the stock compiler, i have no problems with that.
> 
> Anyway I built a windows package overnight to short-circuit this dialogue. I hope the package works for you. I can't do anything about the compiler size.
> 
> See Assets in [14.0.6.1](https://github.com/mulle-cc/mulle-clang-project/releases/tag/14.0.6.1).

First, all of the guides you linked are not for me. The first requires WSL and the later requires MSVC.

Second, you should change your way of naming assets for Windows. WTF mulle-clang-project-14.0.6.1-windows.zip means? Is it for x86 or x86_64? Is it based on LLVM MSVC or LLVM MINGW? You have put up a name that is as bad as possible.

Anyway thank you for your zealot to doing a build overnight just for me. I need a working guide to build for LLVM MINGW more than prebuilt binaries. I could build it myself given I have a working guide.

**Comment by mulle-nat** [comment]
As far as I know there are two sorts of excutables on Windows one is PEF, which is like Windows native and the other is ELF which runs under WSL. I don't think it matters where I build the compiler, but it is a PEF compiler. The executable is 32 bit for max compatibility (i.e. -> windows :)). If you can execute a WHATEVER.EXE you should be able to run mulle-clang.exe, be it in MINGW or in cmd.exe or Visual Studio.

If you have problems building the compiler under MINGW which is AFAIK the same environment as "Bash for Windows", you have to be more specific. How I would do it, and I haven't done this in a few years:

* read [BUILD_MULLE_CLANG.md](https://github.com/mulle-cc/mulle-clang-project/blob/mulle/14.0.6/clang/BUILD_MULLE_CLANG.md) to get the basic "Bash for Windows" environment going. Get more up to date pre-requisites if possible.
* possibly try [install-prerequisites](https://github.com/mulle-cc/mulle-clang-project/blob/mulle/14.0.6/clang/bin/install-prerequisites) or at least look at it to see, what's needed
* pick [clang/bin/cmake-msbuild.windows](https://github.com/mulle-cc/mulle-clang-project/blob/mulle/14.0.6/clang/bin/cmake-msbuild.windows) and adjust the generator so it produces a Makefile for MINGW. (you need mulle-replace from [mulle-nat/mulle-project](https://github.com/mulle-nat/mulle-project) or hand-edit the files manually)
* Don't waste your time if you don't have enough disk space or too little RAM
* If it don't work, put up an issue here or over there in mulle-cc, with *specific* errors. I can't promise that I can fix it, but I will try. 

> The very old way of doing it with [install-mulle-clang](https://github.com/mulle-cc/mulle-clang-project/blob/mulle/10.0.0/clang/bin/install-mulle-clang) doesn't work anymore, since llvm moved to a mono-repo.

I can't write you a better guide, because I don't know more about it, than what's written down.

**Comment by mulle-nat** [comment]
Also, coming to think of it, `mulle-clang-project` is just `llvm` with some patches. So, if someone is building llvm for your pet platform, copy the method and substitute the sources. It should work.

**Comment by 3oheicrw** [comment]
@mulle-nat How could you disable llvm tools from building? I opened your Windows build and I can only see `mulle-clang-cl` and `mulle-clang-nm`. BTW, after messing with it for a whole night I'm now able to build my own mulle-clang. The problem is -DLLVM_TOOLS_ENABLE=OFF seems not really work. Could you give me the full cmake build command of yours? Thanks.

**Comment by 3oheicrw** [comment]
> Also, coming to think of it, `mulle-clang-project` is just `llvm` with some patches. So, if someone is building llvm for **your pet platform**, copy the method and substitute the sources. It should work. The nice thing about doing `llvm` first is, that then you can ask the platform maintainers for help. They probably will have an interest of having `llvm` on their platform or they already know how to. Or you can ask `llvm` how to build it on that platform. With `mulle-clang-project` you can just ask me.

How arrogant!

These people are building for my **pet platform** (MSYS2):

https://github.com/mstorsjo/llvm-mingw/releases

https://github.com/brechtsanders/winlibs_mingw/releases

https://github.com/niXman/mingw-builds-binaries/releases

**Comment by 3oheicrw** [comment]
@mulle-nat I now have my LLVM-14.0.6-win64.zip that is just about 85.6 MB, the size you can never dream of after spending almost two days messing with MSYS2 and this document (https://llvm.org/docs/CMake.html). If I could disable llvm tools I can get it even smaller. The build scripts on https://github.com/mstorsjo/llvm-mingw suggested that I can do so but only when building individual components of LLVM and put up everything together step by step that I'm unwilling to do. BTW, goodbye you arrogant dude. The ticket is solved and will be closed.

**Comment by 3oheicrw** [comment]
Here is the cmake build commands:

https://gist.github.com/3oheicrw/b2cc0a3365354c915f1887175e44b595

**Comment by mulle-nat** [comment]
Dude, no love is lost here. You've been making wild accusations with little substance the whole thread over and you were generally unpleasant to deal with. 

I actually appreciated you trying out the project and putting effort into it getting it to run on windows with MSYS2, where I have very limited experience. I will take a look at your build commands and try to incorporate your improvements into the next release. Thank you for that. 

So anyway, about llvm-tools, I specifically select the projects I want to compile with `-DLLVM_ENABLE_PROJECTS="libcxxabi;libcxx;compiler-rt;clang"`. It's in the [script](https://github.com/mulle-cc/mulle-clang-project/blob/mulle/14.0.6/clang/bin/cmake-msbuild.windows#L28) I linked above. That's all I know how to reduce the amount of stuff being compiled. 
Before packing I remove the stuff I don't need in [#28](https://github.com/mulle-cc/mulle-clang-project/blob/mulle/14.0.6/clang/bin/cmake-msbuild.windows#L73)  (at least on other platforms. I don't remember anymore, why I commented it out on windows).

As to the linker error, my guess is that you are using a non-gcc linker and it doesn't know the special place where the gcc libraries are hardcoded in. You would probably need to find it and add it to `LDFLAGS`.

**Comment by 3oheicrw** [comment]
> So anyway, about llvm-tools, I specifically select the projects I want to compile with `-DLLVM_ENABLE_PROJECTS="libcxxabi;libcxx;compiler-rt;clang"`. It's in the [script](https://github.com/mulle-cc/mulle-clang-project/blob/mulle/14.0.6/clang/bin/cmake-msbuild.windows#L28) I linked above. That's all I know how to reduce the amount of stuff being compiled. Before packing I remove the stuff I don't need in [#28](https://github.com/mulle-cc/mulle-clang-project/blob/mulle/14.0.6/clang/bin/cmake-msbuild.windows#L73) (at least on other platforms. I don't remember anymore, why I commented it out on windows).

It seems you linked the llvm document but you have never read it. Maybe clang-cl simply uses MSVC tools so it default doesn't build llvm-tools. You didn't do anything magically here. My cmake command is more sophisticated than you. BTW you are doing it the wrong way. `libcxxabi;libcxx` should be put in `-DLLVM_ENABLE_RUNTIMES` instead of `-DLLVM_ENABLE_PROJECTS`

> As to the linker error, my guess is that you are using a non-gcc linker and it doesn't know the special place where the gcc libraries are (which is possibly hardcoded in the gcc linker). You would need to find that directory and add it to `LDFLAGS`.

What a nonsense statement! Isn't the clang compiler default to use llvm linker lld? lld is of course non-gcc linker. So clang is unable to compile llvm?

BTW, the problem is solved here: https://github.com/msys2/MINGW-packages/issues/13667#issuecomment-1286918355

**Comment by mulle-nat** [comment]
So I guess that wraps it up to everybodys happiness. 🙄
